### ISSUE TITLE
receive only empty dataframes - reuters.com links probably broken/changed?

### ISSUE THREAD

**Issue by arthwer** [ViniciusWovst/reuterspy#3]
Get only empty dataframes. Reuters.com links changed i.e. the links used within the code are broken?

Here an example of my input:
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0] on linux

from reuterspy import Reuters
reuters = Reuters()
ticker_list = ['NFLX.O']
df = reuters.get_income_statement(ticker_list)
print(df.head())
Empty DataFrame
Columns: []
Index: []

using within the browser the link provided in the code (reuterspy/blob/main/reuterspy/utils/api.py), i.e.
https://www.reuters.com/companies/api/getFetchCompanyFinancials/NFLX.O
-> receive the response: we can't find that page

or within the browser the link coded in reuterspy/blob/main/reuterspy/__init__.py , i.e.
https://www.reuters.com/companies/NFLX.O/key-metrics
-> redirects to https://www.reuters.com/markets/companies/NFLX.O/key-metrics/price-and-volume

**Comment by EdSaiedi** [comment]
Same issue here.

**Comment by ViniciusWovst** [comment]
The Reuters change their links, now has other structure
